package hello;

import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestMapping;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;


import hello.model.Calendar;
import hello.repository.CalendarRepository;

@RestController
public class MainController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CalendarRepository calendarRepository;

    @GetMapping(path="/add") // Map ONLY GET Requests
    public @ResponseBody String addNewCalendar (@RequestParam String name
            , @RequestParam String description) {
        Calendar n = new Calendar();
        n.setName(name);
        n.setDescription(description);
        calendarRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Calendar> getAllCallendars() {
        // This returns a JSON or XML with the users
        return calendarRepository.findAll();
    }

    @RequestMapping("/")
    public String index() {
        return "Greetings from Spring Boot!";
    }

}